spring.application.name=config-service
server.port=8888

# Mode natif : lit les configs depuis le dossier configs/
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=classpath:/configs

# Actuator
management.endpoints.web.exposure.include=health,info
