server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /joueurs {
        proxy_pass http://joueur-service:8081;
        proxy_set_header Host $host;
    }

    location /parties {
        proxy_pass http://partie-service:8083;
        proxy_set_header Host $host;
    }

    location /scores {
        proxy_pass http://score-service:8084;
        proxy_set_header Host $host;
    }

    location /mots {
        proxy_pass http://dictionnaire-service:8082;
        proxy_set_header Host $host;
    }
}
