server.port=8083
spring.datasource.url=jdbc:h2:file:/data/partiedb;AUTO_SERVER=TRUE
spring.jpa.hibernate.ddl-auto=update
dictionnaire.service.url=${DICTIONNAIRE_SERVICE_URL:http://dictionnaire-service:8082}
score.service.url=${SCORE_SERVICE_URL:http://score-service:8084}
