apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
  namespace: motus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
        - name: discovery-service
          image: motus/discovery-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8761
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 20
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  namespace: motus
spec:
  selector:
    app: discovery-service
  ports:
    - port: 8761
      targetPort: 8761
      nodePort: 30761
  type: NodePort
